[2025-08-05 15:06:12,256] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
[2025-08-05 15:06:22,703] INFO drf_case.middleware - 📡 GET /health/ from 172.18.0.7 took 0.27s
[2025-08-05 15:06:34,870] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:06:34,880] WARNING django.request - Unauthorized: /api/token/
[2025-08-05 15:06:35,425] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:06:35,958] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:06:35,961] INFO drf_case.middleware - 📡 POST /api/token/refresh/ from 127.0.0.1 took 0.00s
[2025-08-05 15:06:36,550] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.32s
[2025-08-05 15:06:36,835] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.28s
[2025-08-05 15:06:37,114] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.28s
[2025-08-05 15:06:37,392] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.28s
[2025-08-05 15:06:43,086] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
[2025-08-05 15:06:44,443] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:06:44,448] INFO flights.views - Yeni uçuş oluşturuldu: TK9999 - İzmir → Madrid
[2025-08-05 15:06:44,451] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:06:45,519] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:06:45,525] INFO flights.views - Yeni uçuş oluşturuldu: TK8888 - Antalya → Rome
[2025-08-05 15:06:45,526] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:06:46,602] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:06:46,606] INFO flights.views - Yeni uçuş oluşturuldu: TK7777 - Ankara → Vienna
[2025-08-05 15:06:46,607] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:06:47,672] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:06:47,678] INFO flights.views - Uçuş silindi: TK0000 - Test Origin → Test Destination
[2025-08-05 15:06:47,681] INFO drf_case.middleware - 📡 DELETE /api/flights/16/ from 127.0.0.1 took 0.01s
[2025-08-05 15:06:48,776] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.28s
[2025-08-05 15:06:48,782] INFO drf_case.middleware - 📡 GET /api/flights/17/ from 127.0.0.1 took 0.00s
[2025-08-05 15:06:49,887] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.28s
[2025-08-05 15:06:49,890] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:06:49,896] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:06:50,959] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:06:50,962] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:06:50,966] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:06:52,015] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:06:52,018] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:06:52,023] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:06:53,082] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:06:53,086] INFO flights.views - 📦 DB'den alındı ve cache'e yazıldı.
[2025-08-05 15:06:53,087] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:06:53,918] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:06:53,918] WARNING django.request - Unauthorized: /api/flights/
[2025-08-05 15:06:54,997] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:06:55,000] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:06:55,005] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:06:56,083] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.28s
[2025-08-05 15:06:56,124] INFO flights.views - Uçuş güncellendi: TK1234 - Ankara → Berlin
[2025-08-05 15:06:56,125] INFO drf_case.middleware - 📡 PUT /api/flights/38/ from 127.0.0.1 took 0.04s
[2025-08-05 15:06:57,228] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:06:57,236] INFO drf_case.middleware - 📡 GET /api/flights/41/ from 127.0.0.1 took 0.00s
[2025-08-05 15:06:58,362] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.28s
[2025-08-05 15:06:58,367] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:06:59,467] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:06:59,472] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:00,536] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:07:00,541] INFO drf_case.middleware - 📡 DELETE /api/crew/11/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:01,608] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:07:01,612] INFO drf_case.middleware - 📡 GET /api/crew/12/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:02,705] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.29s
[2025-08-05 15:07:02,711] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:03,788] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:07:03,794] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:04,867] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:07:04,872] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:05,679] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:05,680] WARNING django.request - Unauthorized: /api/crew/
[2025-08-05 15:07:06,754] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:07:06,758] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:06,758] WARNING django.request - Bad Request: /api/crew/
[2025-08-05 15:07:07,824] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:07:07,830] INFO drf_case.middleware - 📡 PUT /api/crew/24/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:13,888] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:07:44,421] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.00s
[2025-08-05 15:07:49,347] INFO drf_case.middleware - 📡 GET / from 172.18.0.7 took 0.28s
[2025-08-05 15:08:15,216] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
[2025-08-05 15:08:45,991] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:09:17,134] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.51s
[2025-08-05 15:16:04,066] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:16:05,607] INFO drf_case.middleware - 📡 GET / from 172.18.0.7 took 0.26s
[2025-08-05 15:16:34,825] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:16:42,653] INFO drf_case.middleware - 📡 GET /health/ from 172.18.0.7 took 0.26s
[2025-08-05 15:16:47,869] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:16:47,871] WARNING django.request - Unauthorized: /api/token/
[2025-08-05 15:16:48,409] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:16:48,943] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:16:48,947] INFO drf_case.middleware - 📡 POST /api/token/refresh/ from 127.0.0.1 took 0.00s
[2025-08-05 15:16:49,520] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.30s
[2025-08-05 15:16:49,791] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.27s
[2025-08-05 15:16:50,058] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.26s
[2025-08-05 15:16:50,324] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.26s
[2025-08-05 15:16:57,308] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:16:57,312] INFO flights.views - Yeni uçuş oluşturuldu: TK9999 - İzmir → Madrid
[2025-08-05 15:16:57,315] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:16:58,377] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:16:58,382] INFO flights.views - Yeni uçuş oluşturuldu: TK8888 - Antalya → Rome
[2025-08-05 15:16:58,383] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:16:59,445] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:16:59,449] INFO flights.views - Yeni uçuş oluşturuldu: TK7777 - Ankara → Vienna
[2025-08-05 15:16:59,450] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:00,517] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:00,523] INFO flights.views - Uçuş silindi: TK0000 - Test Origin → Test Destination
[2025-08-05 15:17:00,526] INFO drf_case.middleware - 📡 DELETE /api/flights/16/ from 127.0.0.1 took 0.01s
[2025-08-05 15:17:01,589] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:01,594] INFO drf_case.middleware - 📡 GET /api/flights/17/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:02,648] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:02,651] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:17:02,656] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:17:03,715] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:17:03,718] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:17:03,722] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:17:04,772] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:04,775] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:17:04,780] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:17:05,608] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:17:05,864] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:05,868] INFO flights.views - 📦 DB'den alındı ve cache'e yazıldı.
[2025-08-05 15:17:05,868] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:06,662] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:06,662] WARNING django.request - Unauthorized: /api/flights/
[2025-08-05 15:17:07,728] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:17:07,730] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:17:07,735] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:17:08,822] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:17:08,860] INFO flights.views - Uçuş güncellendi: TK1234 - Ankara → Berlin
[2025-08-05 15:17:08,861] INFO drf_case.middleware - 📡 PUT /api/flights/38/ from 127.0.0.1 took 0.04s
[2025-08-05 15:17:09,930] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:09,937] INFO drf_case.middleware - 📡 GET /api/flights/41/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:11,053] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:11,057] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:12,115] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:12,120] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:13,168] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:13,174] INFO drf_case.middleware - 📡 DELETE /api/crew/11/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:14,228] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:14,234] INFO drf_case.middleware - 📡 GET /api/crew/12/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:15,285] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:17:15,290] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:16,366] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:17:16,371] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:17,456] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:17:17,461] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:18,311] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:18,311] WARNING django.request - Unauthorized: /api/crew/
[2025-08-05 15:17:19,454] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.29s
[2025-08-05 15:17:19,458] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:17:19,459] WARNING django.request - Bad Request: /api/crew/
[2025-08-05 15:17:20,587] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:17:20,593] INFO drf_case.middleware - 📡 PUT /api/crew/24/ from 127.0.0.1 took 0.01s
[2025-08-05 15:17:36,387] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:41:24,197] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:41:54,974] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:42:25,764] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:42:31,673] INFO drf_case.middleware - 📡 GET /dispatch.asp from 172.18.0.7 took 0.01s
[2025-08-05 15:42:31,675] WARNING django.request - Not Found: /dispatch.asp
[2025-08-05 15:42:38,351] INFO drf_case.middleware - 📡 GET /health/ from 172.18.0.7 took 0.27s
[2025-08-05 15:42:56,262] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.00s
[2025-08-05 15:42:58,051] INFO drf_case.middleware - 📡 GET / from 172.18.0.7 took 0.28s
[2025-08-05 15:42:58,377] INFO drf_case.middleware - 📡 GET /favicon.ico from 172.18.0.7 took 0.28s
[2025-08-05 15:42:58,378] WARNING django.request - Not Found: /favicon.ico
[2025-08-05 15:43:03,628] ERROR django.request - Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "users_user" does not exist
LINE 1: ...", "users_user"."email", "users_user"."role" FROM "users_use...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/views.py", line 46, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/serializers.py", line 73, in validate
    data = super().validate(attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "users_user" does not exist
LINE 1: ...", "users_user"."email", "users_user"."role" FROM "users_use...
                                                             ^

[2025-08-05 15:43:03,633] INFO drf_case.middleware - 📡 POST /api/token/ from 172.18.0.7 took 0.37s
[2025-08-05 15:43:21,003] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:43:21,005] WARNING django.request - Unauthorized: /api/token/
[2025-08-05 15:43:21,555] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.28s
[2025-08-05 15:43:22,087] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:22,090] INFO drf_case.middleware - 📡 POST /api/token/refresh/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:22,669] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.30s
[2025-08-05 15:43:22,942] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:23,215] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:23,487] INFO drf_case.middleware - 📡 POST /api/users/register/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:26,763] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:30,469] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:43:30,474] INFO flights.views - Yeni uçuş oluşturuldu: TK9999 - İzmir → Madrid
[2025-08-05 15:43:30,477] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:43:31,557] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:31,562] INFO flights.views - Yeni uçuş oluşturuldu: TK8888 - Antalya → Rome
[2025-08-05 15:43:31,563] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:32,637] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:43:32,641] INFO flights.views - Yeni uçuş oluşturuldu: TK7777 - Ankara → Vienna
[2025-08-05 15:43:32,642] INFO drf_case.middleware - 📡 POST /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:33,714] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:33,721] INFO flights.views - Uçuş silindi: TK0000 - Test Origin → Test Destination
[2025-08-05 15:43:33,724] INFO drf_case.middleware - 📡 DELETE /api/flights/16/ from 127.0.0.1 took 0.01s
[2025-08-05 15:43:34,800] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.26s
[2025-08-05 15:43:34,806] INFO drf_case.middleware - 📡 GET /api/flights/17/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:35,899] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.28s
[2025-08-05 15:43:35,903] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:43:35,909] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:43:37,007] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:37,010] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:43:37,014] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:43:38,096] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:38,099] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:43:38,103] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:43:39,197] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:39,201] INFO flights.views - 📦 DB'den alındı ve cache'e yazıldı.
[2025-08-05 15:43:39,202] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:40,011] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:40,011] WARNING django.request - Unauthorized: /api/flights/
[2025-08-05 15:43:41,077] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:41,080] INFO flights.views - 🔍 Filtreleme/sayfalama var, doğrudan DB'den çekiliyor
[2025-08-05 15:43:41,084] INFO drf_case.middleware - 📡 GET /api/flights/ from 127.0.0.1 took 0.01s
[2025-08-05 15:43:42,174] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:42,211] INFO flights.views - Uçuş güncellendi: TK1234 - Ankara → Berlin
[2025-08-05 15:43:42,212] INFO drf_case.middleware - 📡 PUT /api/flights/38/ from 127.0.0.1 took 0.04s
[2025-08-05 15:43:43,290] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:43,296] INFO drf_case.middleware - 📡 GET /api/flights/41/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:44,448] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:44,453] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:45,533] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:45,538] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:46,676] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:46,681] INFO drf_case.middleware - 📡 DELETE /api/crew/11/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:47,755] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:47,760] INFO drf_case.middleware - 📡 GET /api/crew/12/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:48,833] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:48,839] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:49,914] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:49,920] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:51,011] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:51,016] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:51,844] INFO drf_case.middleware - 📡 GET /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:51,844] WARNING django.request - Unauthorized: /api/crew/
[2025-08-05 15:43:52,926] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:52,930] INFO drf_case.middleware - 📡 POST /api/crew/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:52,931] WARNING django.request - Bad Request: /api/crew/
[2025-08-05 15:43:54,028] INFO drf_case.middleware - 📡 POST /api/token/ from 127.0.0.1 took 0.27s
[2025-08-05 15:43:54,034] INFO drf_case.middleware - 📡 PUT /api/crew/24/ from 127.0.0.1 took 0.00s
[2025-08-05 15:43:57,516] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:44:20,268] ERROR django.request - Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "users_user" does not exist
LINE 1: ...", "users_user"."email", "users_user"."role" FROM "users_use...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/views.py", line 46, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/serializers.py", line 73, in validate
    data = super().validate(attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "users_user" does not exist
LINE 1: ...", "users_user"."email", "users_user"."role" FROM "users_use...
                                                             ^

[2025-08-05 15:44:20,273] INFO drf_case.middleware - 📡 POST /api/token/ from 172.18.0.7 took 0.34s
[2025-08-05 15:44:28,361] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
[2025-08-05 15:44:59,183] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:46:53,762] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:47:24,503] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.25s
[2025-08-05 15:47:55,237] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.26s
[2025-08-05 15:48:25,976] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.26s
[2025-08-05 15:48:34,294] INFO drf_case.middleware - 📡 GET / from 172.18.0.7 took 0.25s
[2025-08-05 15:48:56,560] INFO drf_case.middleware - 📡 GET /health/ from 172.18.0.7 took 0.26s
[2025-08-05 15:48:56,743] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:49:10,485] ERROR django.request - Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "users_user" does not exist
LINE 1: ...", "users_user"."email", "users_user"."role" FROM "users_use...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/views.py", line 46, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/serializers.py", line 73, in validate
    data = super().validate(attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "users_user" does not exist
LINE 1: ...", "users_user"."email", "users_user"."role" FROM "users_use...
                                                             ^

[2025-08-05 15:49:10,489] INFO drf_case.middleware - 📡 POST /api/token/ from 172.18.0.7 took 0.36s
[2025-08-05 15:49:27,543] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
[2025-08-05 15:49:58,028] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.00s
[2025-08-05 15:50:28,807] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:50:40,003] INFO drf_case.middleware - 📡 POST /api/token/ from 172.18.0.7 took 0.54s
[2025-08-05 15:50:40,004] WARNING django.request - Unauthorized: /api/token/
[2025-08-05 15:50:59,578] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:51:30,086] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.00s
[2025-08-05 15:51:53,887] INFO drf_case.middleware - 📡 GET / from 172.18.0.7 took 0.27s
[2025-08-05 15:53:41,655] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.26s
[2025-08-05 15:54:12,422] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:54:31,835] INFO drf_case.middleware - 📡 POST /api/token/ from 172.18.0.7 took 0.58s
[2025-08-05 15:54:43,204] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:55:13,990] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
[2025-08-05 15:55:44,749] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:56:15,553] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
[2025-08-05 15:56:46,408] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
[2025-08-05 15:56:57,400] INFO drf_case.middleware - 📡 GET / from 172.18.0.7 took 0.28s
[2025-08-05 15:57:17,165] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:57:47,933] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.26s
[2025-08-05 15:58:11,975] INFO drf_case.middleware - 📡 GET / from 172.18.0.7 took 0.27s
[2025-08-05 15:58:18,738] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:58:49,504] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.27s
[2025-08-05 15:59:20,293] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 15:59:50,801] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.00s
[2025-08-05 16:00:21,591] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.28s
[2025-08-05 16:00:24,382] INFO drf_case.middleware - 📡 GET /login.rsp from 172.18.0.7 took 0.01s
[2025-08-05 16:00:24,383] WARNING django.request - Not Found: /login.rsp
[2025-08-05 16:00:52,106] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.00s
[2025-08-05 16:00:59,484] INFO drf_case.middleware - 📡 POST /api/token/ from 172.18.0.7 took 0.56s
[2025-08-05 16:01:02,776] INFO drf_case.middleware - 📡 POST /api/token/ from 172.18.0.7 took 0.54s
[2025-08-05 16:01:22,881] INFO drf_case.middleware - 📡 GET /health/ from 127.0.0.1 took 0.29s
